export const majorLanguages = [
  { code: "ar", name: "Arabic", nativeName: "العربية", direction: "RTL", priority: 0 },
  { code: "en", name: "English", nativeName: "English", direction: "LTR", priority: 1 },
  { code: "fr", name: "French", nativeName: "Français", direction: "LTR", priority: 2 },
  { code: "de", name: "German", nativeName: "Deutsch", direction: "LTR", priority: 3 },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", direction: "LTR", priority: 4 },
  { code: "es", name: "Spanish", nativeName: "Español", direction: "LTR", priority: 5 },
  { code: "it", name: "Italian", nativeName: "Italiano", direction: "LTR", priority: 6 },
  { code: "pt", name: "Portuguese", nativeName: "Português", direction: "LTR", priority: 7 },
  { code: "ru", name: "Russian", nativeName: "Русский", direction: "LTR", priority: 8 },
  { code: "zh", name: "Chinese", nativeName: "中文", direction: "LTR", priority: 9 },
  { code: "ja", name: "Japanese", nativeName: "日本語", direction: "LTR", priority: 10 },
  { code: "ko", name: "Korean", nativeName: "한국어", direction: "LTR", priority: 11 },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", direction: "LTR", priority: 12 },
  { code: "ur", name: "Urdu", nativeName: "اردو", direction: "RTL", priority: 13 },
  { code: "fa", name: "Persian", nativeName: "فارسی", direction: "RTL", priority: 14 },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", direction: "LTR", priority: 15 },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", direction: "LTR", priority: 16 },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", direction: "LTR", priority: 17 },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", direction: "LTR", priority: 18 },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", direction: "LTR", priority: 19 },
  { code: "pl", name: "Polish", nativeName: "Polski", direction: "LTR", priority: 20 },
  { code: "sv", name: "Swedish", nativeName: "Svenska", direction: "LTR", priority: 21 },
  { code: "no", name: "Norwegian", nativeName: "Norsk", direction: "LTR", priority: 22 },
  { code: "da", name: "Danish", nativeName: "Dansk", direction: "LTR", priority: 23 },
  { code: "fi", name: "Finnish", nativeName: "Suomi", direction: "LTR", priority: 24 },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", direction: "LTR", priority: 25 },
  { code: "he", name: "Hebrew", nativeName: "עברית", direction: "RTL", priority: 26 },
  { code: "th", name: "Thai", nativeName: "ไทย", direction: "LTR", priority: 27 },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", direction: "LTR", priority: 28 },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", direction: "LTR", priority: 29 }
];
