import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 36, fontFamily: "Helvetica", color: "#0f172a" },
  header: { borderBottom: "1px solid #dbeafe", paddingBottom: 14, marginBottom: 18 },
  title: { fontSize: 22, fontWeight: 700 },
  subtitle: { marginTop: 4, fontSize: 10, color: "#64748b" },
  grid: { display: "flex", flexDirection: "row", gap: 12, marginBottom: 12 },
  box: { flex: 1, border: "1px solid #e2e8f0", borderRadius: 8, padding: 12 },
  label: { fontSize: 8, color: "#64748b", textTransform: "uppercase", marginBottom: 3 },
  value: { fontSize: 11, marginBottom: 8 },
  tableHeader: { display: "flex", flexDirection: "row", backgroundColor: "#eff6ff", padding: 8, fontSize: 9, fontWeight: 700 },
  tableRow: { display: "flex", flexDirection: "row", borderBottom: "1px solid #e2e8f0", padding: 8, fontSize: 9 },
  col: { flex: 1 },
  footer: { marginTop: 22, borderTop: "1px solid #e2e8f0", paddingTop: 10, fontSize: 9, color: "#64748b" },
  signature: { marginTop: 28, display: "flex", flexDirection: "row", gap: 20 },
  signatureBox: { flex: 1, borderTop: "1px solid #94a3b8", paddingTop: 6, fontSize: 9, color: "#64748b" }
});

type InvoicePdfInput = {
  company: { name: string; email?: string | null; phone?: string | null; taxNumber?: string | null; defaultCurrency: string };
  invoice: {
    number: string;
    issueDate: Date;
    dueDate?: Date | null;
    subtotal: number;
    taxTotal: number;
    total: number;
    currencyCode: string;
    customer?: { name: string; email?: string | null; phone?: string | null } | null;
    items: Array<{ description: string; quantity: number; unitPrice: number; taxRate: number; total: number }>;
  };
};

export async function generateInvoicePdf(input: InvoicePdfInput) {
  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>KIM-ERB Invoice</Text>
          <Text style={styles.subtitle}>{input.company.name} | {input.company.email ?? ""} | {input.company.phone ?? ""}</Text>
        </View>
        <View style={styles.grid}>
          <View style={styles.box}>
            <Text style={styles.label}>Invoice Number</Text>
            <Text style={styles.value}>{input.invoice.number}</Text>
            <Text style={styles.label}>Issue Date</Text>
            <Text style={styles.value}>{input.invoice.issueDate.toLocaleDateString()}</Text>
            <Text style={styles.label}>Due Date</Text>
            <Text style={styles.value}>{input.invoice.dueDate?.toLocaleDateString() ?? "-"}</Text>
          </View>
          <View style={styles.box}>
            <Text style={styles.label}>Customer</Text>
            <Text style={styles.value}>{input.invoice.customer?.name ?? "Walk-in customer"}</Text>
            <Text style={styles.label}>Tax Number</Text>
            <Text style={styles.value}>{input.company.taxNumber ?? "-"}</Text>
            <Text style={styles.label}>Currency</Text>
            <Text style={styles.value}>{input.invoice.currencyCode}</Text>
          </View>
        </View>
        <View style={styles.tableHeader}>
          <Text style={styles.col}>Item</Text>
          <Text style={styles.col}>Qty</Text>
          <Text style={styles.col}>Price</Text>
          <Text style={styles.col}>Tax</Text>
          <Text style={styles.col}>Total</Text>
        </View>
        {input.invoice.items.map((item, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.col}>{item.description}</Text>
            <Text style={styles.col}>{item.quantity}</Text>
            <Text style={styles.col}>{item.unitPrice.toFixed(2)}</Text>
            <Text style={styles.col}>{item.taxRate}%</Text>
            <Text style={styles.col}>{item.total.toFixed(2)}</Text>
          </View>
        ))}
        <View style={styles.grid}>
          <View style={styles.box}>
            <Text style={styles.label}>Subtotal</Text>
            <Text style={styles.value}>{input.invoice.subtotal.toFixed(2)}</Text>
            <Text style={styles.label}>Tax</Text>
            <Text style={styles.value}>{input.invoice.taxTotal.toFixed(2)}</Text>
            <Text style={styles.label}>Total</Text>
            <Text style={styles.value}>{input.invoice.total.toFixed(2)} {input.invoice.currencyCode}</Text>
          </View>
        </View>
        <View style={styles.signature}>
          <Text style={styles.signatureBox}>Prepared by</Text>
          <Text style={styles.signatureBox}>Customer signature</Text>
        </View>
        <Text style={styles.footer}>Generated by KIM-ERB. This document is print-ready.</Text>
      </Page>
    </Document>
  );
}

type CompanyProfileInput = {
  company: Record<string, string | null | undefined>;
};

export async function generateCompanyProfilePdf({ company }: CompanyProfileInput) {
  const rows = [
    ["Company", company.name],
    ["Commercial Registration", company.registrationNo],
    ["Tax Number", company.taxNumber],
    ["Owner", company.ownerName],
    ["Owner Username", company.ownerUsername],
    ["Company Email", company.email],
    ["Phone", company.phone],
    ["Country / City", [company.country, company.city].filter(Boolean).join(" / ")],
    ["Language", company.defaultLanguage],
    ["Currency", company.defaultCurrency],
    ["Subscription", company.planName],
    ["Activation Status", company.status],
    ["Login URL", company.loginUrl],
    ["Created Date", company.createdAt]
  ];
  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>KIM-ERB Company Profile</Text>
          <Text style={styles.subtitle}>Ultimate business management platform</Text>
        </View>
        {rows.map(([label, value]) => (
          <View key={label} style={styles.tableRow}>
            <Text style={styles.col}>{label}</Text>
            <Text style={styles.col}>{value || "-"}</Text>
          </View>
        ))}
        <View style={styles.signature}>
          <Text style={styles.signatureBox}>Platform Admin</Text>
          <Text style={styles.signatureBox}>Company Owner</Text>
        </View>
        <Text style={styles.footer}>KIM-ERB profile document. Keep this with company onboarding records.</Text>
      </Page>
    </Document>
  );
}

type SubscriptionSummaryInput = {
  company: Record<string, string | null | undefined>;
};

export async function generateSubscriptionSummaryPdf({ company }: SubscriptionSummaryInput) {
  const rows = [
    ["Company", company.name],
    ["Owner", company.ownerName],
    ["Owner Email", company.ownerEmail],
    ["Plan", company.planName],
    ["Subscription Status", company.subscriptionStatus],
    ["Starts At", company.startsAt],
    ["Ends At", company.endsAt],
    ["Billing Currency", company.defaultCurrency],
    ["Monthly Price", company.monthlyPrice],
    ["Annual Price", company.annualPrice],
    ["Company Status", company.status],
    ["Generated At", company.generatedAt]
  ];
  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>KIM-ERB Subscription Summary</Text>
          <Text style={styles.subtitle}>Platform billing and subscription record</Text>
        </View>
        {rows.map(([label, value]) => (
          <View key={label} style={styles.tableRow}>
            <Text style={styles.col}>{label}</Text>
            <Text style={styles.col}>{value || "-"}</Text>
          </View>
        ))}
        <View style={styles.signature}>
          <Text style={styles.signatureBox}>Billing Admin</Text>
          <Text style={styles.signatureBox}>Authorized Signature</Text>
        </View>
        <Text style={styles.footer}>Generated by KIM-ERB billing foundation.</Text>
      </Page>
    </Document>
  );
}

export async function generateKeyValuePdf({
  title,
  subtitle,
  rows
}: {
  title: string;
  subtitle?: string;
  rows: Array<[string, string | number | null | undefined]>;
}) {
  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>{subtitle ?? "Generated by KIM-ERB"}</Text>
        </View>
        {rows.map(([label, value]) => (
          <View key={label} style={styles.tableRow}>
            <Text style={styles.col}>{label}</Text>
            <Text style={styles.col}>{value == null || value === "" ? "-" : String(value)}</Text>
          </View>
        ))}
        <View style={styles.signature}>
          <Text style={styles.signatureBox}>Prepared by</Text>
          <Text style={styles.signatureBox}>Approved by</Text>
        </View>
        <Text style={styles.footer}>This document is print-ready and can be archived or shared with the customer.</Text>
      </Page>
    </Document>
  );
}
